CREATE OR REPLACE PROCEDURE PROC_USER_UPDATE
(
	V_UM_CODE 			IN 		USER_MAIN.UM_CODE%TYPE,
	V_UM_NAME 			IN 		USER_MAIN.UM_NAME%TYPE,
	V_UM_ID 			IN 		USER_MAIN.UM_ID%TYPE,
	V_UM_PWD 			IN 		USER_MAIN.UM_PWD%TYPE,
	V_UM_DEPART_CD 		IN 		USER_MAIN.UM_DEPART_CD%TYPE,
	V_UM_POSITION_BCODE IN 		USER_MAIN.UM_POSITION_BCODE%TYPE,
	V_UM_POSITION 		IN 		USER_MAIN.UM_POSITION%TYPE,
	V_UM_LEVEL 			IN 		USER_MAIN.UM_LEVEL%TYPE,
	V_UM_TEL1 			IN 		USER_MAIN.UM_TEL1%TYPE,
	V_UM_TEL2 			IN 		USER_MAIN.UM_TEL2%TYPE,
	V_UM_TEL3 			IN 		USER_MAIN.UM_TEL3%TYPE,
	V_UM_INLINE 		IN 		USER_MAIN.UM_INLINE%TYPE,
	V_UM_HIRE_Y 		IN 		USER_MAIN.UM_HIRE_Y%TYPE,
	V_UM_HIRE_M 		IN 		USER_MAIN.UM_HIRE_M%TYPE,
	V_UM_HIRE_D 		IN 		USER_MAIN.UM_HIRE_D%TYPE,
	V_UM_VACATION_CNT 	IN 		USER_MAIN.UM_VACATION_CNT%TYPE,
	V_UM_USE_FLAG 		IN 		USER_MAIN.UM_USE_FLAG%TYPE,
	V_UD_GENDER 		IN 		USER_DETAIL.UD_GENDER%TYPE,
	V_UD_BIRTH_Y 		IN 		USER_DETAIL.UD_BIRTH_Y%TYPE,
	V_UD_BIRTH_M 		IN 		USER_DETAIL.UD_BIRTH_M%TYPE,
	V_UD_BIRTH_D 		IN 		USER_DETAIL.UD_BIRTH_D%TYPE,
	V_UD_CALENDER_KIND 	IN 		USER_DETAIL.UD_CALENDER_KIND%TYPE,
	V_UD_TEL1 			IN 		USER_DETAIL.UD_TEL1%TYPE,
	V_UD_TEL2 			IN 		USER_DETAIL.UD_TEL2%TYPE,
	V_UD_TEL3 			IN 		USER_DETAIL.UD_TEL3%TYPE,
	V_UD_MOBILE1 		IN 		USER_DETAIL.UD_MOBILE1%TYPE,
	V_UD_MOBILE2 		IN 		USER_DETAIL.UD_MOBILE2%TYPE,
	V_UD_MOBILE3 		IN 		USER_DETAIL.UD_MOBILE3%TYPE,
	V_UD_ZIP1 			IN 		USER_DETAIL.UD_ZIP1%TYPE,
	V_UD_ZIP2 			IN 		USER_DETAIL.UD_ZIP2%TYPE,
	V_UD_ADDR1 			IN 		USER_DETAIL.UD_ADDR1%TYPE,
	V_UD_ADDR2 			IN 		USER_DETAIL.UD_ADDR2%TYPE,
	V_UD_HOMEPAGE 		IN 		USER_DETAIL.UD_HOMEPAGE%TYPE,
	V_UD_WEDDING_FLAG 	IN 		USER_DETAIL.UD_WEDDING_FLAG%TYPE,
	V_UD_WEDDING_Y 		IN 		USER_DETAIL.UD_WEDDING_Y%TYPE,
	V_UD_WEDDING_M 		IN 		USER_DETAIL.UD_WEDDING_M%TYPE,
	V_UD_WEDDING_D 		IN 		USER_DETAIL.UD_WEDDING_D%TYPE,
	V_UD_HOBBY 			IN 		USER_DETAIL.UD_HOBBY%TYPE,
	V_UD_RESUME 		IN 		USER_DETAIL.UD_RESUME%TYPE,
	V_UD_INTRODUCTION 	IN 		USER_DETAIL.UD_INTRODUCTION%TYPE,
	V_UD_MEMO 			IN 		USER_DETAIL.UD_MEMO%TYPE,
	V_UI_FACE_NAME 		IN 		USER_IMAGE.UI_FACE_NAME%TYPE,
	V_UI_FACE_PATH 		IN 		USER_IMAGE.UI_FACE_PATH%TYPE,
	V_UI_SIGN_NAME 		IN 		USER_IMAGE.UI_SIGN_NAME%TYPE,
	V_UI_SIGN_PATH 		IN 		USER_IMAGE.UI_SIGN_PATH%TYPE,
	V_WORK_USER 		IN 		USER_MAIN.UM_CODE%TYPE
)
IS
BEGIN

	/*===== USER_MAIN UPDATE =====*/
	
	UPDATE USER_MAIN
	SET
	
		UM_NAME = V_UM_NAME,
		UM_ID = V_UM_ID,
		UM_PWD = V_UM_PWD,
		UM_DEPART_CD = V_UM_DEPART_CD,
		UM_POSITION_BCODE = V_UM_POSITION_BCODE,
		UM_POSITION = V_UM_POSITION,
		UM_LEVEL = V_UM_LEVEL,
		UM_TEL1 = V_UM_TEL1,
		UM_TEL2 = V_UM_TEL2,
		UM_TEL3 = V_UM_TEL3,
		UM_INLINE = V_UM_INLINE,
		UM_HIRE_Y = V_UM_HIRE_Y,
		UM_HIRE_M = V_UM_HIRE_M,
		UM_HIRE_D = V_UM_HIRE_D,
		UM_VACATION_CNT = V_UM_VACATION_CNT,
		UM_USE_FLAG = V_UM_USE_FLAG,
		UM_EDIT_USER = V_WORK_USER,
		UM_EDIT_DATE = SYSDATE
	
	WHERE (UM_CODE = V_UM_CODE);
	
	
	
	/*===== USER_DETAIL UPDATE =====*/
	
	UPDATE USER_DETAIL
	SET
	
		UD_GENDER = V_UD_GENDER,
		UD_BIRTH_Y = V_UD_BIRTH_Y,
		UD_BIRTH_M = V_UD_BIRTH_M,
		UD_BIRTH_D = V_UD_BIRTH_D,
		UD_CALENDER_KIND = V_UD_CALENDER_KIND,
		UD_TEL1 = V_UD_TEL1,
		UD_TEL2 = V_UD_TEL2,
		UD_TEL3 = V_UD_TEL3,
		UD_MOBILE1 = V_UD_MOBILE1,
		UD_MOBILE2 = V_UD_MOBILE2,
		UD_MOBILE3 = V_UD_MOBILE3,
		UD_ZIP1 = V_UD_ZIP1,
		UD_ZIP2 = V_UD_ZIP2,
		UD_ADDR1 = V_UD_ADDR1,
		UD_ADDR2 = V_UD_ADDR2,
		UD_HOMEPAGE = V_UD_HOMEPAGE,
		UD_WEDDING_FLAG = V_UD_WEDDING_FLAG,
		UD_WEDDING_Y = V_UD_WEDDING_Y,
		UD_WEDDING_M = V_UD_WEDDING_M,
		UD_WEDDING_D = V_UD_WEDDING_D,
		UD_HOBBY = V_UD_HOBBY,
		UD_RESUME = V_UD_RESUME,
		UD_INTRODUCTION = V_UD_INTRODUCTION,
		UD_MEMO = V_UD_MEMO,
		UD_EDIT_USER = V_WORK_USER,
		UD_EDIT_DATE = SYSDATE
	
	WHERE (UD_UM_CODE = V_UM_CODE);
	
	
	
	
	/*===== USER_IMAGE UPDATE =====*/
	
	UPDATE USER_IMAGE
	SET
	
		UI_FACE_NAME = V_UI_FACE_NAME,
		UI_FACE_PATH = V_UI_FACE_PATH,
		UI_SIGN_NAME = V_UI_SIGN_NAME,
		UI_SIGN_PATH = V_UI_SIGN_PATH,
		UI_GET_USER = V_WORK_USER,
		UI_GET_DATE = SYSDATE
	
	WHERE (UI_UM_CODE = V_UM_CODE);
	
	
COMMIT;
	
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;	
	
END
;

/	