SELECT 	SC_USER STRUSER, 
		SC_YY STRYY, SC_MM STRDD,
		STR_DD STRDD, SC_SEQ STRSEQ,
		SC_TITLE STRTITLE, SC_DETAIL_COMMENT,
		SC_START_HOUR STRSTART_HOUR, SC_START_MINUTE STRSTART_MINUTE,
		SC_END_HOUR STREND_HOUR, SC_END_MINUTE STREND_MINUTE,
		SC_TERM_HOUR STRTERM_HOUR, SC_TERM_MINUTE STRTERM_MINUTE,
		SC_SCH_KIND STRSCH_KIND_CD, CM_SCH.CM_NAME STRSCH_KIND_NM,
		SC_WORK_KIND STRSCH_KIND_CD, CM_WORK.CM_NAME STRWORK_KIND_NM,
		SC_DISCLOSURE STRDISCLOSURE_CD, CM_DISCLOSURE.CM_NAME STRDISCLOSURE_NM
		
FROM 	SCHEDULE SC
		
ORDER BY SC_USER, SC_YY, SC_MM, SC_DD, SC_SEQ
