CREATE OR REPLACE VIEW VI_DEPART
AS
	SELECT 	L1.DE_DCODE CO_CODE, 		L1.DE_NAME CO_NAME, 
			L1.DE_SORT CO_SORT, 		L1.DE_LEVEL CO_LEVEL,
			L2.DE_DCODE DEPART_CODE, 	L2.DE_NAME SNAME,
			L2.DE_SORT DEPART_SORT, 	L2.DE_LEVEL DEPART_LEVEL,
			L3.DE_DCODE TEAM_CODE, 		L3.DE_NAME TNAME,
			L3.DE_SORT TEAM_SORT, 		L3.DE_LEVEL TEAM_LEVEL
	FROM 	DEPART L1
			LEFT OUTER JOIN DEPART L2 	ON 	(L1.DE_DCODE = L2.DE_PCODE)
										AND (L2.DE_USE_FLAG = 1)
			LEFT OUTER JOIN DEPART L3 	ON 	(L2.DE_DCODE = L3.DE_PCODE)
										AND (L3.DE_USE_FLAG = 1)
	WHERE 	(L1.DE_DCODE = '000')
	ORDER BY L1.DE_SORT, L2.DE_SORT, L3.DE_SORT;
	

CREATE OR REPLACE VIEW VI_USER_MAIN
AS
	SELECT 	L1.DE_DCODE CO_CODE, 		L1.DE_NAME CO_NAME, 
			L1.DE_SORT CO_SORT, 		L1.DE_LEVEL CO_LEVEL,
			L2.DE_DCODE DEPART_CODE, 	L2.DE_NAME SNAME,
			L2.DE_SORT DEPART_SORT, 	L2.DE_LEVEL DEPART_LEVEL,
			L3.DE_DCODE TEAM_CODE, 		L3.DE_NAME TNAME,
			L3.DE_SORT TEAM_SORT, 		L3.DE_LEVEL TEAM_LEVEL,
			UM.UM_CODE UM_CODE, UM_NAME,
			UM.UM_POSITION POSITION_CODE, CM.CM_NAME POSITION_NAME,
			CM.CM_SORT POSITION_SORT 
	FROM 	DEPART L1
			LEFT OUTER JOIN DEPART L2 	ON 	(L1.DE_DCODE = L2.DE_PCODE)
										AND (L2.DE_USE_FLAG = 1)
			LEFT OUTER JOIN DEPART L3 	ON 	(L2.DE_DCODE = L3.DE_PCODE)
										AND (L3.DE_USE_FLAG = 1)
			LEFT OUTER JOIN USER_MAIN UM ON (L3.DE_DCODE = UM.UM_DEPART_CD)
			LEFT OUTER JOIN CODE_MANAGE CM ON (UM.UM_POSITION_BCODE = CM.CM_BCODE)
											AND (UM.UM_POSITION = CM.CM_SCODE)
	WHERE 	(L1.DE_DCODE = '000')
	ORDER BY L1.DE_SORT, L2.DE_SORT, L3.DE_SORT, POSITION_SORT;

	
	
	